export const LOGINASIMS = 'LOGINASIMS';
export const LOGOUTASIMS = 'LOGOUTASIMS';
export const USER_BASIC = 'BASIC';
export const FIRST_TIME = 'FIRST_TIME';
export const COMPANY = 'COMPANY';
export const UPDATE_FIRST_RUN_COMPANY = 'UPDATE_FIRST_RUN_COMPANY'; // for one time api request
export const ADD_COMPANY = 'ADD_COMPANY';
export const ADD_VENDOR_PRODUCTS = 'ADD_VENDOR_PRODUCTS';
export const USERS = 'USERS';
export const UPDATE_FIRST_RUN_USERS = 'UPDATE_FIRST_RUN_USERS'; // for one time api request
export const ADD_USER = 'ADD_USER';
export const USER_PROFILE = 'USER_PROFILE';
export const APPROVE_USER = 'APPROVE_USER';
export const USER_COMPANY = 'USER_COMPANY';
export const PRODUCTS = 'PRODUCTS';
export const UPDATE_FIRST_RUN_PRODUCTS = 'UPDATE_FIRST_RUN_PRODUCTS'; // for one time api request
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_VERSION = 'ADD_VERSION';
export const ADD_MACHINE = 'ADD_MACHINE';
export const UPDATE_MACHINE_STATUS = 'UPDATE_MACHINE_STATUS'; // when product is allocating in order
export const ORDERS = 'ORDERS';
export const UPDATE_FIRST_RUN_ORDERS = 'UPDATE_FIRST_RUN_ORDERS'; // for one time api request
export const ADD_UNPROCEED_ORDER = 'ADD_UNPROCEED_ORDER';
export const REMOVE_UNPROCEED_ORDER = 'REMOVE_UNPROCEED_ORDER';
export const UNPROCEED_ADD_PRODUCT = 'UNPROCEED_ADD_PRODUCT';
export const UNPROCEED_REMOVE_PRODUCT = 'UNPROCEED_REMOVE_PRODUCT';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_FIRST_RUN_TEAM = 'UPDATE_FIRST_RUN_TEAM';
export const UPDATE_FIRST_RUN_MEDIA = 'UPDATE_FIRST_RUN_MEDIA';
export const UPDATE_MEDIA_ITEMS = 'UPDATE_MEDIA_ITEMS';
export const UPDATE_TEAM_ITEMS = 'UPDATE_TEAM_ITEMS';
export const POST_MEDIA_ITEMS = 'POST_MEDIA_ITEMS';
export const DELETE_MEDIA = 'DELETE_MEDIA';
export const UNPUBLISHED_MEDIA = 'UNPUBLISHED_MEDIA';
export const UPDATE_MEDIA = 'UPDATE_MEDIA';
export const CREATE_JOB = 'CREATE_JOB';
export const FETCH_JOB = 'FETCH_JOB';
export const FETCH_JOB_BY_ID = 'FETCH_JOB_BY_ID';
export const UPDATE_JOB = 'UPDATE_JOB';
export const UNPUBLISHED_JOB = 'UNPUBLISHED_JOB';
export const DELETE_JOB = 'DELETE_JOB';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const BLOG_CONTENT_OPEN = 'BLOG_CONTENT_OPEN'
export const BLOG_ITEM = 'BLOG_ITEM'
export const BLOG_ITEM_BY_ID = 'BLOG_ITEM_BY_ID'
export const ADD_BLOG_ITEM = 'ADD_BLOG_ITEM'
export const UPDATE_BLOG_ITEM = 'UPDATE_BLOG_ITEM'
export const DELETE_BLOG = 'DELETE_BLOG'
export const UNPUBLISHED_BLOG = 'UNPUBLISHED_BLOG'
export const ADD_IMAGE_GALLARY = 'ADD_IMAGE_GALLARY'
export const IMAGE_GALLARY = 'IMAGE_GALLARY'